services:
  - type: web
    name: projetogeradordesp
    env: python
    buildCommand: pip install poetry && poetry install
    startCommand: poetry run streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11